services:
  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: sied_clients_v3
    restart: always
    ports:
      - "5432:5432"
